# name: Node.js CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with: { version: 7 }

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      # install deps
      - run: pnpm install --frozen-lockfile

      # build .app file
      - run: pnpm dist:pack
